name: package-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda
        with:
          miniconda-version: "latest"
          activate-environment: dev
      - run: pip list
